##################################################
## HOUSE MODE
##################################################
# Set house mode to evening
- alias: 'Time of Day :: Evening'
  id: '000001'
  action:
  - data:
      entity_id: input_select.house_mode
      option: Evening
    service: input_select.select_option
  condition: []
  trigger:
  - at: '17:00:00'
    platform: time

# Set house mode to night
- alias: 'Time of Day :: Night'
  id: '000002'
  action:
  - data:
      entity_id: input_select.house_mode
      option: Night
    service: input_select.select_option
  - data:
      entity_id: switch.fang_light_night
    service: switch.turn_on
  - data:
      entity_id: switch.fang_light_day
    service: switch.turn_off
  condition: []
  trigger:
  - at: '21:00:00'
    platform: time

# Set house mode to morning
- alias: 'Time of Day :: Morning'
  id: '000003'
  action:
  - data:
      entity_id: input_select.house_mode
      option: Morning
    service: input_select.select_option
  - data:
      entity_id: switch.fang_light_day
    service: switch.turn_on
  - data:
      entity_id: switch.fang_light_night
    service: switch.turn_off
  condition: []
  trigger:
  - at: 06:00:00
    platform: time

# Set house mode to day
- alias: 'Time of Day :: Day'
  id: '000004'
  action:
  - data:
      entity_id: input_select.house_mode
      option: Day
    service: input_select.select_option
  condition: []
  trigger:
  - at: '12:00:00'
    platform: time

# When the house is empty
- alias: 'House Mode :: Unoccupied'
  id: '000005'
  action:
  - data:
      entity_id: input_select.presence
      option: Away
    service: input_select.select_option
  - data:
      entity_id: group.office_lights
    service: light.turn_off
  - data:
      entity_id: group.office_switches
    service: switch.turn_off
  - data:
      entity_id: group.living_room_lights
    service: light.turn_off
  condition: []
  trigger:
  - entity_id: group.family
    platform: state
    from: home
    to: not_home

# When the house is occupied
- alias: 'House Mode :: Occupied'
  id: '000006'
  action:
  - data:
      entity_id: input_select.presence
      option: Home
    service: input_select.select_option
  condition: []
  trigger:
  - entity_id: group.family
    platform: state
    from: not_home
    to: home

##################################################
## LEAVE HOME ACTIVITIES
##################################################

# Michael
- alias: 'Leave :: Home - Michael'
  id: '000007'
  action:
  - data:
      entity_id: media_player.musicoffice
    service: media_player.media_stop
  - data:
      message: Michael left home
    service: notify.ios_phonemichael
  - data:
      entity_id: group.office_lights
    service: light.turn_off
  - data:
      entity_id: group.office_switches
    service: switch.turn_off
  condition: []
  trigger:
  - entity_id: device_tracker.phone_michael
    platform: state
    from: home
    to: not_home

# Jennifer
- alias: 'Leave :: Home - Jennifer'
  id: '000008'
  action:
  - data:
      message: Jennifer left home
    service: notify.ios_phonemichael
  condition: []
  trigger:
  - entity_id: device_tracker.user_jennifer
    platform: state
    from: home
    to: not_home

# Alex
- alias: 'Leave :: Home - Alex'
  id: '000009'
  action:
  - data:
      message: Alex left home
    service: notify.ios_phonemichael
  condition: []
  trigger:
  - entity_id: device_tracker.nmap_alex
    platform: state
    from: home
    to: not_home

# Morgann
- alias: 'Leave :: Home - Morgann'
  id: '000010'
  action:
  - data:
      message: Morgann left home
    service: notify.ios_phonemichael
  condition: []
  trigger:
  - entity_id: device_tracker.user_morgann
    platform: state
    from: home
    to: not_home

# Ian
- alias: 'Leave :: Home - Ian'
  id: '000011'
  action:
  - data:
      message: Ian left home
    service: notify.ios_phonemichael
  condition: []
  trigger:
  - entity_id: device_tracker.user_ian
    platform: state
    from: home
    to: not_home

##################################################
## ARRIVE HOME ACTIVITIES
##################################################

#Michael
- alias: 'Arrive :: Home - Michael'
  id: '000012'
  action:
  - data:
      message: Michael is home
    service: notify.ios_phonemichael
  - data:
      entity_id: media_player.musicoffice
    service: media_player.turn_on
  - data:
      entity_id: media_player.musicoffice
      volume_level: 0.4
    service: media_player.volume_set
  - data:
      entity_id: media_player.musicoffice
    service: media_player.media_play
  - data:
      entity_id: switch.office_scentsy_switch
    service: switch.turn_on
  condition: []
  trigger:
  - entity_id: device_tracker.phone_michael
    platform: state
    from: not_home
    to: home

# Jennifer
- alias: 'Arrive :: Home - Jennifer'
  id: '000013'
  action:
  - data:
      message: Jennifer is home
    service: notify.ios_phonemichael
  condition: []
  trigger:
  - entity_id: device_tracker.user_jennifer
    platform: state
    from: not_home
    to: home

# Alex
- alias: 'Arrive :: Home - Alex'
  id: '000014'
  action:
  - data:
      message: Alex is home
    service: notify.ios_phonemichael
  condition: []
  trigger:
  - entity_id: device_tracker.nmap_alex
    platform: state
    from: not_home
    to: home

# Morgann
- alias: 'Arrive :: Home - Morgann'
  id: '000015'
  action:
  - data:
      message: Morgann is home
    service: notify.ios_phonemichael
  condition: []
  trigger:
  - entity_id: device_tracker.user_morgann
    platform: state
    from: not_home
    to: home

# Ian
- alias: 'Arrive :: Home - Ian'
  id: '000016'
  action:
  - data:
      message: Ian is home
    service: notify.ios_phonemichael
  condition: []
  trigger:
  - entity_id: device_tracker.user_ian
    from: not_home
    platform: state
    to: home

##################################################
## LIGHTING
##################################################

# Office Lights
- alias: 'Lighting :: Office Light -- ON by MOTION'
  id: '000017'
  action:
  - data:
      entity_id: light.office_light_level
    service: light.turn_on
  condition:
  - below: '5000'
    condition: numeric_state
    entity_id: sensor.office_motion_luminance
  trigger:
  - entity_id: binary_sensor.office_motion_sensor
    platform: state
    from: 'off'
    to: 'on'

- alias: 'Lighting :: Office light -- OFF by MOTION'
  id: '000018'
  action:
  - data:
      entity_id: light.office_light_level
    service: light.turn_off
  condition: []
  trigger:
  - entity_id: binary_sensor.office_motion_sensor
    platform: state
    from: 'on'
    to: 'off'
    for:
      minutes: 10

# Living Room Lights
- alias: 'Lighting :: Living Room Lamp -- OFF by MOTION at BEDTIME'
  id: '000019'
  action:
  - data:
      entity_id: light.living_room_lamp_l_level
    service: light.turn_off
  condition:
  - condition: state
    entity_id: input_select.house_mode
    state: Bedtime
  trigger:
  - entity_id: binary_sensor.living_room_motion_sensor
    for:
      minutes: 5
    platform: state
    from: 'on'
    to: 'off'

- alias: 'Lighting :: Living Room Lamp -- ON by MOTION at BEDTIME'
  id: '000020'
  action:
  - data:
      brightness_pct: 15
      entity_id: light.living_room_lamp_l_level
    service: light.turn_on
  condition:
  - condition: state
    entity_id: input_select.house_mode
    state: Bedtime
  trigger:
  - entity_id: binary_sensor.living_room_motion_sensor
    platform: state
    to: 'on'

# Sunset
- alias: 'Lighting :: ON at SUNSET'
  id: '000021'
  action:
  - data:
      entity_id: switch.entry_way_lamp_switch
    service: switch.turn_on
  - data:
      brightness_pct: 100
      entity_id: light.front_porch_light_level
    service: light.turn_on
  condition: []
  trigger:
  - event: sunset
    platform: sun

##################################################
## NOTIFICATIONS
##################################################

# Garage door
- alias: 'Notification :: Garage Door -- Open at bedtime'
  id: '000022'
  action:
  - data:
      message: The garage door is OPEN
    service: notify.ios_phonemichael
  condition:
  - condition: state
    entity_id: binary_sensor.garage_overhead_door_sensor
    state: 'on'
  trigger:
  - entity_id: input_select.house_mode
    platform: state
    to: Bedtime

##################################################
## SCENES
##################################################

# Start a movie on Plex in the Media Room
- alias: 'Movie :: Start -- PLEX Media Room'
  id: '000023'
  action:
  - data:
      entity_id: script.start_plex_movie
    service: script.turn_on
  condition: []
  trigger:
  - entity_id: input_boolean.plex_movie
    from: 'off'
    platform: state
    to: 'on'

# Stop a movie on Plex in the Media Room
- alias: 'Movie :: Stop -- PLEX Media Room'
  id: '000024'
  action:
  - data:
      entity_id: script.stop_plex_movie
    service: script.turn_on
  condition: []
  trigger:
  - entity_id: input_boolean.plex_movie
    from: 'on'
    platform: state
    to: 'off'

# Plex Movie
- alias: 'Plex Movie Pause'
  id: '000025'
  action:
  - data:
      entity_id: switch.media_room_lamp_switch
    service: switch.turn_on
  condition: []
  trigger:
  - entity_id: remote.media_room
    from: Playing
    platform: state
    to: Paused
